### ISSUE TITLE
Unit/integration testing

### ISSUE THREAD

**Issue by dotproto** [legitco/gimli#3]
Generic placeholder issue to implement testing on this project. We specifically need to cover:
- Unit testing
- Integration testing
- AngularJS tests

**Comment by dotproto** [comment]
[Mocha & Chai example project](https://github.com/airportyh/testem/tree/master/examples/mocha_chai_simple)

[More Testem example projects](https://github.com/airportyh/testem#example-projects)

**Comment by kelsin** [comment]
Integration testing is working with code coverage. Will be working on unit testing and moving from mocha to testem+mocha later.

**Comment by kelsin** [comment]
We're using Mocha & Chai for unit tests. Sinon for mocking/stubing/spies. Testem as a runner to run all tests (and run them in CI mode). Supertest for integration testing with our express app (With Chai plugins). We're using fakeredis when NODE_ENV=test so that we can clear the db between tests. The only thing left is AngularJS testing so I'm going to open a new issue for that.
